version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: qa
      POSTGRES_PASSWORD: qa
      POSTGRES_DB: qa
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/.chroma
    ports:
      - "8000:8000"
volumes:
  db_data:
  chroma_data:
