name: CI
on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: qa
          POSTGRES_PASSWORD: qa
          POSTGRES_DB: qa
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U qa" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: |
          cd backend
          poetry install --no-root
      - name: Test
        run: |
          cd backend
          poetry run pytest
      - name: Slack notify
        if: failure()
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"CI failed"}' ${{ secrets.SLACK_WEBHOOK }}
